config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [path("admin/", admin.site.urls),
               path('', include('med.urls', namespace='med')),
               path('users/', include('users.urls')),
               ] + static(
                    settings.STATIC_URL,
                    document_root=settings.STATIC_ROOT
                ) + static(
                    settings.MEDIA_URL,
                    document_root=settings.MEDIA_ROOT
                )

med/urls.py
from med.views import ServicesListView, ServicesDetailView, ContactsTemplateView, ServicesMakingListView, \
    AppointmentCreateView, AppointmentUserListView, AppointmentArchiveListView, AppointmentCancelView
from users.views import UsersListView

from django.urls import path
from med.apps import MedConfig

app_name = MedConfig.name

urlpatterns = [
    path('', ServicesListView.as_view(), name='index'),
    path("services/<int:pk>/", ServicesDetailView.as_view(), name="speciality_detail"),
    path('about/', UsersListView.as_view(), name='about'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),

    path('making_an_appointment/', ServicesMakingListView.as_view(), name='making_an_appointment'),
    path('appointments_create/<int:pk>/', AppointmentCreateView.as_view(), name='appointments_create'),
    path('appointments_my/', AppointmentUserListView.as_view(), name='appointments_my'),
    path('appointments_archive/', AppointmentArchiveListView.as_view(), name='appointments_archive'),
    path('appointments_cancel/<int:pk>/', AppointmentCancelView.as_view(), name='appointments_cancel'),

]

med/models.py
from django.db import models

from django.core.exceptions import ValidationError
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}


class Services(models.Model):
    """
    This class represents a service offered by a medical service system.

    Attributes:
    title: The title or name of the service.
    description: A detailed description of the service.
    price: The cost of the service.
    image: An image representing the service.
    title = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание', **NULLABLE)
    price = models.PositiveIntegerField(verbose_name='стоимость')
    image = models.ImageField(upload_to='image/', verbose_name='иконка', **NULLABLE)
    """

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'услуга'
        verbose_name_plural = 'услуги'


class Appointment(models.Model):
    """
    This class represents an appointment record in a medical service system.

    Attributes:
    user: The patient who made the appointment.
    services: The diagnostic service for which the appointment is made.
    doctor: The doctor assigned to the appointment.
    date: The date and time of the appointment.
    result: The results of the diagnostic examination.

    Methods:
    clean_fields: Validates that the appointment date is not in the past.
    """

    user = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='записи', verbose_name='пациент',
                             **NULLABLE)
    services = models.ForeignKey('Services', on_delete=models.CASCADE, related_name='записи',
                                 verbose_name='диагностика', **NULLABLE)
    doctor = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='user', verbose_name='врач')
    date = models.DateTimeField(verbose_name='дата и время приема')
    result = models.TextField(verbose_name='результаты обследования', **NULLABLE)

    def __str__(self):
        return f'{self.user}: {self.date} {self.services}, {self.doctor}'

    class Meta:
        verbose_name = 'запись на диагностику'
        verbose_name_plural = 'записи на диагностику'

    def clean_fields(self, exclude=None):

        super().clean_fields(exclude=exclude)

        now = timezone.now()
        if self.date < now:
            raise ValidationError('Не допускается создавать записи в прошедшем времени')

med/forms.py
from django import forms

from med.models import Appointment


class AppointmentForm(forms.ModelForm):
    """
       Form for managing appointments.

       This form is used to create and update appointment records in the database.
       It inherits from Django's ModelForm and is specifically designed for the Appointment model.
    """

    def __init__(self, *args, **kwargs):
        super(AppointmentForm, self).__init__(*args, **kwargs)
        self.fields['doctor'].queryset = kwargs['initial']['doctor']

    class Meta:
        model = Appointment
        fields = ('doctor', 'date',)

med/views.py
from datetime import datetime

from django.shortcuts import HttpResponseRedirect, get_object_or_404, redirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, TemplateView, CreateView

from med.forms import AppointmentForm
from med.models import Services, Appointment
from users.models import User


class ServicesListView(ListView):
    """
    Display a list of all services.

    Attributes:
    model : Services
        The model class to query for the list of services.
    template_name : str
        The name of the template to render for this view.

    Methods:
    get_queryset()
        Override the default queryset to order services by title.
    post(request, *args, **kwargs)
        Handle POST requests to process form data.
        Save user's contact information and redirect to the same page.
    """

    model = Services
    template_name = 'med/index.html'

    def get_queryset(self):
        queryset = super().get_queryset().order_by('title')
        return queryset

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} / {phone} / {message}')
        data = f'Name: {name}. Phone: {phone}. Message: {message}\n'
        with open('user_data.txt', 'a', encoding='UTF-8') as f:
            f.write(data)
        return HttpResponseRedirect(reverse('med:index'))


class DoctorsListView(ListView):
    """
       Retrieve and return all doctors.

       Parameters:
       None

       Returns:
       queryset : QuerySet
           A QuerySet containing all doctors.
   """

    model = User
    template_name = 'med/about.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset


class ServicesDetailView(DetailView):
    """
    Display detailed information about a service.

    Attributes:
    success_url : str
        The URL to redirect to after successful processing.

    Methods:
    get(request, pk)
        Retrieve and display detailed information about a service.

    Parameters:
    request : HttpRequest
        The request object.
    pk : int
        The primary key of the service to retrieve.

    Returns:
    HttpResponse
        The rendered HTML response with detailed information about the service.
    """

    success_url = reverse_lazy('med:appointments_my')

    def get(self, request, pk):
        services = Services.objects.get(id=pk)
        self.service = Services.objects.get(pk=self.kwargs['pk'])
        self.doctor = self.service.services.filter(services=self.service.pk)
        context = {
            'services': services,
            'doctor': self.doctor,
            'title': services.title,
            'description': services.description
        }
        return render(request, 'med/services.html', context)


class ContactsTemplateView(TemplateView):
    """
    A view for displaying the contacts page.

    Attributes:
    template_name : str
        The name of the template to render for this view.

    Methods:
    get_context_data(self, **kwargs)
        Override the default get_context_data method to add a title to the context.
    post(self, request, *args, **kwargs)
        Handle POST requests to process form data.
        Save user's contact information and redirect to the same page.
    """
    template_name = 'med/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Контакты'
        return context

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'{name} / {phone} / {message}')
        data = f'Name: {name}. Phone: {phone}. Message: {message}\n'
        with open('user_data.txt', 'a', encoding='UTF-8') as f:
            f.write(data)
        return HttpResponseRedirect(reverse('med:contacts'))


class AppointmentCreateView(CreateView):
    """
    A view for creating a new appointment.

    Attributes:
    model : Appointment
        The model class to create a new appointment.
    form_class : AppointmentForm
        The form class to use for creating a new appointment.
    success_url : str
        The URL to redirect to after successfully creating an appointment.

    Methods:
    get_initial(self, **kwargs)
        Override the default get_initial method to set initial values for the form.
    form_valid(self, form, **kwargs)
        Override the default form_valid method to set the user and service for the appointment.
    """
    model = Appointment
    form_class = AppointmentForm
    success_url = reverse_lazy('med:appointments_my')

    def get_initial(self, **kwargs):
        self.service = Services.objects.get(pk=self.kwargs['pk'])
        print(self.service)
        self.doctor = self.service.services.filter(services=self.service.pk)
        return {
            'doctor': self.doctor,
            'date': datetime.now().strftime('%Y-%m-%d'),
        }

    def form_valid(self, form, **kwargs):
        form.instance.user = self.request.user
        form.instance.services = self.service
        return super().form_valid(form)


class AppointmentUserListView(ListView):
    """
    Display a list of appointments made by the current user.

    Attributes:
    model : Appointment
        The model class to query for the list of appointments.
    template_name : str
        The name of the template to render for this view.

    Methods:
    get_queryset()
        Override the default queryset to filter and order appointments.

    Parameters:
    None

    Returns:
    queryset : QuerySet
        A QuerySet containing all appointments made by the current user,
        ordered by date in ascending order. If the user is not authenticated,
        the queryset will be None.
    """

    model = Appointment
    template_name = 'med/appointments_my.html'

    def get_queryset(self):
        user = self.request.user
        current_datetime = datetime.now()

        if user.is_authenticated:  # для зарегистрированных пользователей
            queryset = super().get_queryset().filter(user=user, date__gte=current_datetime).order_by('date')
        else:  # для незарегистрированных пользователей
            queryset = None
        return queryset


class AppointmentArchiveListView(ListView):
    """
    Display a list of past appointments for diagnosis.

    Attributes:
    model : Appointment
        The model class to query for the list of appointments.
    template_name : str
        The name of the template to render for this view.

    Methods:
    get_queryset()
        Override the default queryset to filter and order past appointments.

    Parameters:
    None

    Returns:
    queryset : QuerySet
        A QuerySet containing all past appointments, ordered by date in descending order and then by service.
        If the user is not authenticated, the queryset will be None.
    """

    model = Appointment
    template_name = 'med/appointments_archive.html'

    def get_queryset(self):
        user = self.request.user
        current_datetime = datetime.now()

        if user.is_authenticated:  # для зарегистрированных пользователей
            if user.is_staff or user.is_superuser:  # для работников и суперпользователя
                queryset = super().get_queryset().filter(date__lt=current_datetime).order_by('-date', 'services')
            else:  # для остальных пользователей
                queryset = super().get_queryset().filter(user=user, date__lt=current_datetime).order_by('-date',
                                                                                                        'services')
        else:  # для незарегистрированных пользователей
            queryset = None
        return queryset


class AppointmentCancelView(View):
    """
    A view for canceling an appointment.

    Attributes:
    success_url : str
        The URL to redirect to after successfully canceling an appointment.

    Methods:
    post(self, request, pk, *args, **kwargs)
        Handle POST requests to cancel an appointment.

    Parameters:
    request : HttpRequest
        The request object.
    pk : int
        The primary key of the appointment to cancel.
    args : tuple
        Additional positional arguments.
    kwargs : dict
        Additional keyword arguments.

    Returns:
    HttpResponseRedirect
        A redirect response to the success URL.
    """

    success_url = reverse_lazy('med:appointments_my')

    def post(self, request, pk, *args, **kwargs):
        appointment = get_object_or_404(Appointment, pk=pk)
        appointment.user = None
        appointment.save()
        return redirect(self.success_url)


class ServicesMakingListView(ListView):
    """
    Display a list of all services for making an appointment.

    Attributes:
    model : Services
        The model class to query for the list of services.
    template_name : str
        The name of the template to render for this view.

    Methods:
    get_queryset()
        Override the default queryset to order services by title.

    Parameters:
    None

    Returns:
    queryset : QuerySet
        A QuerySet containing all services ordered by title.
    """

    model = Services
    template_name = 'med/making_an_appointment.html'

    def get_queryset(self):
        queryset = super().get_queryset().order_by('title')
        return queryset

med/templates/med/about.html
{% extends 'med/base.html' %}
{% load my_tags %}
{% load static %}


{% block content %}


<center><h3>История компании :</h3></center>
Наша компания была основана в 2000 году с целью предоставления высококачественных услуг в области медицинской диагностики. Мы стремимся помочь людям сохранить здоровье и вовремя выявить возможные проблемы.

С момента основания нашей компании мы постоянно развиваемся и совершенствуем свои услуги. Мы используем современное оборудование и передовые методы исследования, чтобы обеспечить точность и надёжность результатов. Наши специалисты имеют большой опыт работы и постоянно повышают свою квалификацию.

Мы работаем с пациентами всех возрастов и предоставляем услуги как в частных, так и в государственных медицинских учреждениях. Наша цель — сделать медицинскую диагностику доступной для каждого человека.

За время существования нашей компании мы помогли многим людям получить своевременную и точную диагностику. Мы гордимся тем, что можем внести свой вклад в сохранение здоровья людей.

В будущем мы планируем продолжать развиваться и расширять спектр предоставляемых услуг. Мы хотим стать ещё ближе к нашим клиентам и предоставлять им ещё более качественные услуги.
<br><br>
<center><h3>Миссия :</h3></center>
Мы стремимся помочь людям сохранить здоровье и вовремя выявить возможные проблемы. Мы предоставляем высококачественные услуги в области медицинской диагностики, чтобы наши клиенты могли быть уверены в своём здоровье.
<br><br>
<center><h3>Ценности:</h3></center>
<br>

Профессионализм. Мы используем современное оборудование и передовые методы исследования, чтобы обеспечить точность и надёжность результатов. Наши специалисты имеют большой опыт работы и постоянно повышают свою квалификацию.
Ответственность. Мы несём ответственность за качество предоставляемых услуг и результаты исследований. Мы гарантируем конфиденциальность информации о наших клиентах.
Доступность. Мы стремимся сделать медицинскую диагностику доступной для каждого человека. Мы работаем с пациентами всех возрастов и предоставляем услуги как в частных, так и в государственных медицинских учреждениях.
Забота о клиенте. Мы заботимся о здоровье наших клиентов и готовы предоставить им необходимую помощь и поддержку.
<br><br>
<center><h3>Наши Специалисты :</h3></center>
<br>


<div class="container">
    <div class="row text-center">
        {% for user in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow border-dark h-100">
                <div class="card text-bg-dark border-dark mb-2 h-100" style="max-width: 30rem;">
                    <h4 class="my-0 font-weight-normal">{{ user.first_name }}</h4>
                    <h1 class="card-title pricing-card-title">{{ user.last_name }}</h1>
                </div>
                <div class="card-body">
                    <img src="{{ user.avatar | media_filter }}" width="270" height="300">
                </div>
            </div>
        </div>


        {% endfor %}
{% endblock %}

med/templates/med/appointment_form.html
{% extends 'med/base.html' %}
{% block content %}

<div class="col-6">
    <div class="card">

        <form method="post" enctype="multipart/form-data">
            <div class="card-body">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit" class="btn btn-success">Сохранить</button>
            </div>
        </form>
    </div>
</div>

{% endblock %}

med/templates/med/appointments_archive.html
{% extends 'med/base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
<div class="container marketing">

    <div class="nav-scroller py-1 mb-2">
        <a class="btn btn-success my-6" href="{% url 'med:appointments_my' %}">Назад</a>

    </div>
    <div class="card mb-4 box-shadow">
    </div>
    <div class="col-12 text-center">

        <p></p>
    </div>
    <div class="row">
        {% for object in object_list %}
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">{{ object.diagnostic.title}}</h4>
            </div>
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <h5>Стоимость: {{ object.diagnostic.price}} руб.</h5>
                    <h5>Врач: {{ object.doctor}}</h5>
                    <h5>Дата и время: {{ object.date }}</h5>
                    {% if object.user %}
                    {% if user.is_staff %}
                    <h5>Пациент: {{ object.user }}</h5>
                    {% endif %}
                    {% endif %}
                </ul>
            </div>
        </div>


        {% endfor %}
    </div>
</div>
{% else %}
<h3>Просмотр записей на прием к врачу доступен только авторизованным пользователям</h3>
<h4>Пожалуйста, авторизуйтесь!</h4>
{% endif %}

{% endblock %}

med/templates/med/appointments_my.html
{% extends 'med/base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
<div class="container marketing" xmlns="http://www.w3.org/1999/html">

    <div class="nav-scroller py-1 mb-2">
        <a class="btn btn-success my-6" href="{% url 'med:appointments_archive' %}">Архив прошедших записей</a>

    </div>
    <div class="card mb-4 box-shadow">
    </div>
    <div class="col-12 text-center">
        <a>Мои записи на прием</a>
        <p></p>
    </div>
    <div class="row">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                {% for object in object_list %}
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">{{ object.services.title }}</h3>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4">
                            <h4>Стоимость: {{ object.services.price }} руб.</h4>
                            <h4>Врач: {{ object.doctor}}</h4>
                            <h4>Дата и время: {{ object.date }}</h4>
                            {% if object.result %}
                            <h4>Результат: {{ object.result }}</h4>
                            {% else %}
                            <h4>Результат: </h4>
                            {% endif %}
                            <button class="btn btn-lg btn-block btn-dark" type="submit"
                                    formaction="{% url 'med:appointments_cancel' object.pk %}">Отменить прием
                            </button>
                        </ul>
                    </div>
                </div>

                {% endfor %}
            </div>
        </form>
    </div>

</div>
{% else %}
<h3>Просмотр записей на прием к врачу, доступен только зарегистрированных пользователей</h3>
<h4>Пожалуйста, зарегистрируйтесь!</h4>
{% endif %}

{% endblock %}

med/templates/med/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Sergey Arefev">
    <meta name="generator" content="Hugo 0.84.0">
    <title>{{ title }}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/album/">


    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"



</head>
<body>
<style>
      strong {
        color: red; /* задаёт красный цвет текста */
      }
      .red-link {
        color: red;
        }
      .clip {
        clip-path: polygon(0 0, 100% 0%, 100% calc(100% - 80px), 0 calc(100% - 80px));
        }
      .clip2 {
        clip-path: polygon(0 0, 100% 0%, 100% calc(100%), 0 calc(100%));
        }
      .no-space-top {
        margin-top: -500px;
        }

</style>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">Ваше здоровье — наша цель!</h4>
                    <p class="text-muted"></p>
                </div>
                {% include 'med/includes/inc_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{% url 'med:index' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>

                MED

                <strong>X</strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Тел: +7 777-777-77-77
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Email:&nbsp;&nbsp;	Med@X.ru
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                {{user.email}}<span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main class="">
        <section class="py-2 text-center container">
        <div class="row py-lg-2">
            <div class="col-lg-12 col-md-5 mx-auto">
                <!--h1 class="fw-light">{{ title }}</h1-->
                <p class="lead text-active" style="font-size: 36px;"><b>Точность и профессионализм в каждом исследовании !</b></p>
            </div>
        </div>
    </section>

    <div class="album py-3 bg-light ">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</main>

<footer class="pt-4 my-md-0 pt-md-5 offset-md-2">
        <div class="row">
            <div class="col-12 col-md">
                MedX
                <small class="d-block mb-3 text-muted">&copy; 2020 - {% now 'Y' %}</small>
            </div>
            <div class="col-6 col-md">

            </div>
            <div class="col-6 col-md">

            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="red-link" href="{% url 'med:contacts' %}">Контакты</a></li>
                    <li><a class="red-link" href="{% url 'med:about' %}" >О компании</a></li>
                </ul>
            </div>
        </div>
    </footer>

<script defer src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script defer src="{% static 'js/bootstrap.min.js' %}"></script>


</body>
</html>

med/templates/med/index.html
{% extends 'med/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<style>
      strong {
        color: red; /* задаёт красный цвет текста */
      }
       .black-link {
         color: black;
}
</style>


<div class="row">
    <div class="col-16">
        <p class="text-dark" style="font-size: 18px;">Мы — команда профессионалов в области медицинской диагностики. Наша цель — предоставить вам высококачественные услуги, чтобы вы могли быть уверены в своём здоровье.

<br>Наша компания предлагает широкий спектр услуг по диагностике различных заболеваний. Мы используем современное оборудование и передовые методы исследования, чтобы обеспечить точность и надёжность результатов.

<br>Наши специалисты имеют большой опыт работы и постоянно повышают свою квалификацию. Мы следим за последними тенденциями в медицине и внедряем новые технологии в свою работу.


</p>
    </div>
</div>
<br>
<br>
<div class="row text-start">
<div class="col-lg-9 col-md-12 col-sm-12 offset-md-0" >
        <div id="carouselExampleCaptions" class="carousel slide" data-bs-theme="dark">

            <div class="carousel-inner">
            {% for object in object_list %}
            <div class="carousel-item active">
                <img src="{{ object.image | media_filter }}" class="d-block w-100" alt="..." width="200" height="390">
                <div class="carousel-caption d-none d-md-block">
                    <h2><a href="{% url 'med:speciality_detail' object.pk %}" class="black-link"> {{object.title}}
                    </a></h2>
                    <h6>{{object.description}}
                    </h6>

                </div>
            </div>
            {% endfor %}

  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Предыдущий</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Следующий</span>
  </button>
            </div>
        </div>

<br>
<br>
<br>
<br>

    </div><!-- /.row -->
    <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow" style="border-color: black;">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Ваше сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-dark">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
</div>
</main><!-- /.container -->

{% endblock %}

med/templates/med/making_an_appointment.html
{% extends 'med/base.html' %}
{% load static %}
{% block content %}
<style>

       .black-link {
         color: black;
}
</style>
<h2>Выберете услугу:</h2>
<br>
{% for obj in object_list %}
    <h3><a href="{% url 'med:appointments_create' obj.pk %}" class="black-link"> {{obj.title}}</a> - {{obj.price}} P.
                    </h3>


{% endfor %}

{% endblock %}

med/templates/med/user_appointments.html
{% extends 'med/base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
<div class="container marketing" xmlns="http://www.w3.org/1999/html">

    <div class="nav-scroller py-1 mb-2">
        <a class="btn btn-success my-6" href="{% url 'med:appointments_archive' %}">Архив прошедших записей</a>

    </div>
    <div class="card mb-4 box-shadow">
    </div>
    <div class="col-12 text-center">
        <a>Мои записи на прием</a>
        <p></p>
    </div>
    <div class="row">
        <form method="post">
            {% csrf_token %}
            <div class="row">
                {% for object in object_list %}
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h3 class="my-0 font-weight-normal">{{ object.services.title }}</h3>
                    </div>
                    <div class="card-body">
                        <ul class="list-unstyled mt-3 mb-4">
                            <h4>Стоимость: {{ object.services.price }} руб.</h4>
                            <h4>Врач: {{ object.doctor}}</h4>
                            <h4>Дата и время: {{ object.date }}</h4>
                            {% if object.result %}
                            <h4>Результат: {{ object.result }}</h4>
                            {% else %}
                            <h4>Результат: </h4>
                            {% endif %}
                            <button class="btn btn-lg btn-block btn-dark" type="submit"
                                    formaction="{% url 'med:appointments_cancel' object.pk %}">Отменить прием
                            </button>
                        </ul>
                    </div>
                </div>

                {% endfor %}
            </div>
        </form>
    </div>

</div>
{% else %}
<h3>Просмотр записей на прием к врачу, доступен только зарегистрированных пользователей</h3>
<h4>Пожалуйста, зарегистрируйтесь!</h4>
{% endif %}

{% endblock %}